server:
  port: 8001
  servlet:
    context-path: /justicia/juzgados
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.42.252:3306/justicia 
    username: root
    password: root
eureka:
  instance:
    ip-address: 192.168.42.252
    prefer-ip-address: true
    instance-id: 192.168.42.252:8001    
  client:    
    serviceUrl:
      defaultZone: http://192.168.42.252:8761/eureka
