server:
  port: 8001
  servlet:
    context-path: /justicia/juzgados
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
eureka:
  instance:
    ip-address: 192.168.42.187
    prefer-ip-address: true
    instance-id: 192.168.42.187:8001    
  client:    
    serviceUrl:
      defaultZone: http://192.168.42.187:8761/eureka
