server:
  port: 8002
  servlet:
    context-path: /justicia/jueces   
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.43:3306/justicia
    username: oscar
    password: oscar
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  instance:
    ip-address: 192.168.1.42
    prefer-ip-address: true
    instance-id: 192.168.1.42:8002    
  client:    
    serviceUrl:
      defaultZone: http://192.168.1.42:8761/eureka
