server:
  port: 8001
  servlet:
    context-path: /justicia/juzgados
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.43:3306/justicia 
    username: root
    password: root
eureka:
  instance:
    ip-address: 192.168.1.43
    prefer-ip-address: true
    instance-id: 192.168.1.43:8001    
  client:    
    serviceUrl:
      defaultZone: http://192.168.1.42:8761/eureka
