server:
  port: 9001
  servlet:
    context-path: /justicia/adm    
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.137.1:3306/justicia
    username: oscar
    password: oscar
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  instance:
    ip-address: 192.168.137.1
    prefer-ip-address: true
    instance-id: 192.168.137.1:9001
  client:    
    serviceUrl:
      defaultZone: http://192.168.137.42:8761/eureka
url:
  base:
    servicio:
      ine: http://servicios.ine.es/wstempus/js/ES/VALORES_VARIABLEOPERACION/115/22?page=1  
      opendatasoft:
        localidades: http://public.opendatasoft.com/api/records/1.0/search
